server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./data/vault-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

application:
  jwt:
    # Default JWT secret must be at least 256 bits (32 bytes) long to satisfy HS256 requirements.
    # Please override via environment variables for production deployments.
    secret: change-me-to-a-secure-32-byte-minimum-secret-key
    expiration-minutes: 120
  security:
    cors:
      allowed-origins:
        - http://localhost:4200

logging:
  level:
    com.example.minilastpass: INFO
